name = input("Enter your name: ")
surname = input("Enter your surname: ")
print(" ")
print("This program was written by: "+name+" "+surname)
print(" ")
print("Square")
print(" ")
print("*******************")
print("*******************")
print("*******************")
print("*******************")
print("*******************")
print("*******************")
print("*******************")
print("*******************")
print("*******************")
print("*******************")
print(" ")
print("Diamond")
print(" ")
print("       *          ")
print("      ***         ")
print("     *****        ")
print("    *******       ")
print("   *********      ")
print("  ***********     ")
print(" *************    ")
print("***************   ")
print(" *************    ")
print("  ***********     ")
print("   *********      ")
print("    *******       ")
print("     *****        ")
print("      ***         ")
print("       *          ")
print(" ")
print("Triangle")
print(" ")
print("*")
print("**")
print("***")
print("****")
print("*****")
print("******")
print("********")
print("*********")
print("**********")
print("***********")
print("**********")
print("*********")
print("********")
print("*******")
print("******")
print("*****")
print("****")
print("***")
print("**")
print("*")
print(" ")
print("Heart")
print(" ")
print("  *****     *****   ")
print(" *******   *******  ")
print("********* ********* ")
print("******************* ")
print(" *****************  ")
print("  ***************   ")
print("   *************    ")
print("    ***********     ")
print("     *********      ")
print("      *******       ")
print("       *****        ")
print("        ***         ")
print("         *          ")




